### ISSUE TITLE
Capacitor V3

### ISSUE THREAD

**Issue by EinfachHans** [hinddeep/capacitor-file-selector#8]
Is this Plugin still maintained and are you going to migrate to V3?

**Comment by MilotH2** [comment]
I also have issues for Capacitor V3. It says Deployment target is 11 for this, while the capacitor and latest xcode requires 12, and ionic capacitor v3 wont build on deployment target 11.

**Comment by EinfachHans** [comment]
For anyone getting here: I created a own Plugin which was created for V3: https://github.com/EinfachHans/capacitor-file-select

**Comment by MilotH2** [comment]
@EinfachHans I will give it a try, thanks :)

This works, thanks.
